---
title: "R Notebook"
output:
  html_notebook: default
  word_document: default
---

```{r}
setwd("C:/Users/brian/OneDrive/3 Data Science/Data Science Project")
library(ggplot2)
library(datasets)
library(mice)
library(VIM)
library(reshape)
library(data.table)
library(graphics)
library(car)
library(maps)
library(plyr)
```

```{r}
county_facts <- read.csv("county_facts.csv")
pres16results <- read.csv("pres16results.csv")
pe16rwvd9 <- read.csv("pres.elect16.results.wide.votes.dec9.csv")
primres <- read.csv("primary_results.csv")
exitpolls <- read.csv("exitpollsdatacnn04022017.csv")
elec2012 <- read.csv("2012_pres_results.txt")

data(county.fips, state.fips)
fipscode = county.fips
```

```{r}
# #Testing each data set for missingness
# #County facts
# aggr1_plotfacts <- aggr(county_facts, col = c('Blue','Purple'), numbers = TRUE, sortVars = TRUE, cex.axis = .8, gap = 3, ylab = c('County Facts Histogram of Missing Data','Pattern'))
# 
# #presidential election 2016 results
# aggr1pres <- aggr(pres16results, col = c('Blue','Purple'), numbers = TRUE, sortVars = TRUE, cex.axis = .8, gap = 3, ylab = c('Presidential Results Histogram of Missing Data','Pattern'))
# 
# #wide results
# aggr1wide <- aggr(pe16rwvd9, col = c('Blue','Purple'), numbers = TRUE, sortVars = TRUE, cex.axis = .8, gap = 3, ylab = c('Wide Presidential Results Histogram of Missing Data','Pattern'))
# 
# #primary dataset
# aggr1prim <- aggr(primres, col = c('Blue','Purple'), numbers = TRUE, sortVars = TRUE, cex.axis = .8, gap = 3, ylab = c('Primary Result Histogram of Missing Data','Pattern'))
# 
# #Exit polls
# aggrexit <- aggr(exitpolls, col = c('Blue','Purple'), numbers = TRUE, sortVars = TRUE, cex.axis = .8, gap = 3, ylab = c('Exit Polls Histogram of Missing Data','Pattern'))


```

```{r}
########## CLEANING THE WIDE VOTES DATA SET #########
pe16rwvd9 <- read.csv("pres.elect16.results.wide.votes.dec9.csv")

setnames(pe16rwvd9, old = c(8:13, 15:19, 21:39), new = c("other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other", "other"))

pe16rwvd9 <- unique(melt(pe16rwvd9, id=c(1:7,14,20), na.rm = FALSE))

pe16rwvd9 <- pe16rwvd9[order(pe16rwvd9$fips) , ]



setnames(pe16rwvd9, old = c("value", "variable"), new= c("Votes", "Candidates"))
statesvotes<-subset(pe16rwvd9,  is.na(pe16rwvd9$county)) 
pe16rwvd9 = pe16rwvd9[!(pe16rwvd9$county %in% statesvotes$county),]
statesvotes <- statesvotes[c(-(1:3))]

#########CLEANING THE pres 16 RESULTS DATA ########
#new data frame with places if missing election data
nodata <- data.frame(pres16results[18352:18475, 1:2])

#find rows where most are  cols 3:9 are NA
pres16results <- pres16results[-c(18352:18475),]

########## CLEANING THE COUNTY FACTS DATA SET #########

county_facts=county_facts[, !(colnames(county_facts) %in% c("AGE135214", "LFE305213", "MAN450207", "WTN220207", "LND110210"))]


stfips = data.frame(fips=1000*state.fips$fips)
#Adding non-continental states to data frame: Alaska 2000, Hawaii 15000
stfips[64,] <- 2000
stfips[65,] <- 15000

#Creating the states dataframe
statesfacts = county_facts[(county_facts$fips %in% stfips$fips),]
statesfacts$state_abbreviation <- NULL



#Removing states from county column in county facts and subsetting to a nw data frame
county_facts = county_facts[!(county_facts$fips %in% stfips$fips),]


#To get longitude and latitude of counties and states
states <- map_data("state")
counties <- map_data("county")


```

```{r}
# #Checking missingness after cleaning
# #County facts
# aggr1_plotfacts <- aggr(county_facts, col = c('Blue','Purple'), numbers = TRUE, sortVars = TRUE, cex.axis = .8, gap = 3, ylab = c('County Facts Histogram of Missing Data','Pattern'))
# 
# #presidential election 2016 results
# aggr1pres <- aggr(pres16results, col = c('Blue','Purple'), numbers = TRUE, sortVars = TRUE, cex.axis = .8, gap = 3, ylab = c('Presidential Results Histogram of Missing Data','Pattern'))
# 
# #wide results
# aggr1meltwide <- aggr(pe16rwvd9, col = c('Blue','Purple'), numbers = TRUE, sortVars = TRUE, cex.axis = .8, gap = 3, ylab = c('Wide Presidential Results Histogram of Missing Data','Pattern'))
# 
# #primary dataset
# aggr1prim <- aggr(primres, col = c('Blue','Purple'), numbers = TRUE, sortVars = TRUE, cex.axis = .8, gap = 3, ylab = c('Primary Result Histogram of Missing Data','Pattern'))
# 
# #Exit polls
# aggrexit <- aggr(exitpolls, col = c('Blue','Purple'), numbers = TRUE, sortVars = TRUE, cex.axis = .8, gap = 3, ylab = c('Exit Polls Histogram of Missing Data','Pattern'))


```


```{r}

race = county_facts[-1,c(1:4, 11:18)]
setnames(race, old=c("PST045214", "state_abbreviation", "RHI125214","RHI225214", "RHI325214", "RHI425214", "RHI525214", "RHI625214", "RHI725214", 'RHI825214'), new=c("Population", "sa", "White", "Black", "Native American", "Asian", "Pacific Islander", "2+ Races", "Latino", "White/Not Latino"))

#The racial values converted to decimals and then multiplied by total population to get the whole number value of votes per county by race

bpop = 0.01*race['Black']*race['Population']
wpop = 0.01*race['White']*race['Population']
napop = 0.01*race['Native American']*race['Population']
apop = 0.01*race['Asian']*race['Population']
pipop = 0.01*race['Pacific Islander']*race['Population']
mupop = 0.01*race['2+ Races']*race['Population']
lpop = 0.01*race['Latino']*race['Population']
epop = 0.01*race['White/Not Latino']*race['Population']


#Sources list voter total of 137-139 Million

race =data.frame(race$fips, race$area_name, race$sa,  race$Population, wpop, bpop,  napop, apop, pipop, mupop, lpop, epop)


#Exit polls data
eprace <- exitpolls[c(15:19, 21), c(4:8)]
eprace[c(2:5)] <-replace(eprace[c(2:5)], values =0.01*eprace[c(2:5)] )

epraceT = eprace[1:3] #Transpose of races

epracegen <- exitpolls[c(22:28), c(4:8)]
epracegenT = eprace[1:3] #Transpose of races


```



Baplots of Trump and Clinto supporters by race
```{r}

#barplot of total number of people by race
barplot(eprace$Clinton_perc, col=rainbow(8), names.arg = c("White", "Black", "Latino", "Asian", "Other", 'Non-White'), main = "Total Hillary Support by Race/Ethnicity", xlab = 'Races', ylab = "Percentage of Support")


#barplot of total number of people by race
barplot(eprace$Trump_perc, col=rainbow(8), names.arg = c("White", "Black", "Latino", "Asian", "Other", 'Non-White'), main = "Total Trump Support by Race/Ethnicity", xlab = 'Races', ylab = "Percentage of Support")
```

Clinton and Trump supporters by Race and Gender
```{r}
#barplot of total number of people by race
barplot(epracegen$Clinton_perc , col=rainbow(8), names.arg = c("White Men", "White Women", "Black Men", "Black Women", "Latino Men", "Latinas", "Others"), main = "Total Hillary Support by Race/Ethnicity and Gender", xlab = 'Races', ylab = "Percentage of Support")


#barplot of total number of people by race
barplot(epracegen$Trump_perc, col=rainbow(8), names.arg = c("White Men", "White Women", "Black Men", "Black Women", "Latino Men", "Latinas", "Others"), main = "Total Trump Support by Race/Ethnicity and Gender", xlab = 'Races', ylab = "Percentage of Support")
```


```{r}
#Showing how many counties 
barplot(table(pe16rwvd9$lead), col=rainbow(2), ylab = "Number of Counties", main="Counties Won by Leading Candidate", ylim = c(0,3000))

#Summary of whole number of votes per county by race
summary(race[c(5:10)])

```


```{r}
#GGplot bar graph of Total counties per state

bar1 <- ggplot(data=race, aes(x=race.sa))
bar1 + geom_bar() +   xlab("Counties") +  ylab("Number of Counties") + ggtitle("Counties per State") 

```

```{r}
#Helps visualizing missing data
marginplot(race[c(3, 5)])


white = race$White*0.01*eprace$Clinton_perc
black = race$Black*0.01*eprace$Clinton_perc

asian = race$Asian*0.01*eprace$Clinton_perc
latino = race$White*0.01*eprace$Clinton_perc
other = 0.01*eprace$Clinton_perc

```

 ```{r} 
barplot(white) 
qqPlot(white) 

#White votes versus all populations   
scatterplot(white, race$race.Population, xlim = c(0, 200000), ylim = c(0,1000000),  xlab="Number of White Votes", ylab="Total Population per County") 

#Wisconsin White Voting whole number values  
WIWhitesSubset = subset(race, race.sa=="WI", select = c(race.area_name, White, race.sa)) 

barplot(WIWhitesSubset$White, col = rainbow(20), main = "Wisconsin Total White Votes by County ", ylab = "Number of Votes",  names.arg =WIWhitesSubset$race.area_name, cex.names=0.5, las=3) 


#California White Voting whole number values  
CAWhitesSubset = subset(race, race.sa=="CA", select = c(race.area_name, race.Population, White, race.sa)) 

barplot(CAWhitesSubset$White, col = rainbow(20), main = "California Total White Votes by County ", ylab = "Number of Votes",  names.arg =CAWhitesSubset$race.area_name, cex.names=0.5, las=3) 

#Scatterplot of the relationship between population size and race 
scatterplot(CAWhitesSubset$White, CAWhitesSubset$race.Population, main="California White Vote Versus Population", xlim = c(0, 300000), ylim=c(0, 400000)) 
``` 


```{r}
# #Helps visualizing missing data
# marginplot(race[c(3, 6)])
# 
# barplot(race$Black)
# qqPlot(race$Black)
# 
# #Black votes versus all populations  
# scatterplot(race$Black, race$race.Population, xlim = c(0, 4000000), ylim = c(0,5000000),  xlab="Number of Black Votes", ylab="Total Population per County")
# 
# #Wisconsin Black Voting whole number values 
# WIBlacksSubset = subset(race, race.sa=="WI", select = c(race.area_name, race.Population, Black, race.sa))
# 
# barplot(WIBlacksSubset$Black, col = rainbow(20), main = "Wisconsin Total Black Votes by County ", ylab = "Number of Votes", names.arg =WIBlacksSubset$race.area_name, cex.names=0.5, las=3)
# 
# #California Black Voting whole number values 
# CABlacksSubset = subset(race, race.sa=="CA", select = c(race.area_name, race.Population, Black, race.sa))
# 
# 
# 
# barplot(CABlacksSubset$Black, col = rainbow(20), main = "California Total Black Votes by County ", ylab = "Number of Votes",  names.arg =CABlacksSubset$race.area_name, cex.names=0.5, las=3)
# 
# 
# #Scatterplot of the relationship between population size and race
# scatterplot(CABlacksSubset$Black, CABlacksSubset$race.Population, main="California Black Vote Versus Population", xlim = c(0, 15000), ylim=c(0, 400000))


```



```{r}
#Helps visualizing missing data
# marginplot(race[c(3, 8)])
# 
# barplot(race$Asian)
# qqPlot(race$Asian)
# 
# #Asian votes versus all populations  
# scatterplot(race$Asian, race$race.Population, xlim = c(0, 4000000), ylim = c(0,5000000),  xlab="Number of Asian Votes", ylab="Total Population per County")
# 
# #Wisconsin Asian Voting whole number values 
# WIAsiansSubset = subset(race, race.sa=="WI", select = c(race.area_name, race.Population, Asian, race.sa))
# 
# barplot(WIAsiansSubset$Asian, col = rainbow(20), main = "Wisconsin Total Votes by County ", ylab = "Number of Votes",  names.arg =WIWhitesSubset$race.area_name, cex.names=0.5, las=3)
# 
# #California Asian Voting whole number values 
# CAAsiansSubset = subset(race, race.sa=="CA", select = c(race.area_name, race.Population, Asian, race.sa))
# 
# barplot(CAAsiansSubset$Asian, col = rainbow(20), main = "California Total Votes by County ", ylab = "Number of Votes",  names.arg =CAAsiansSubset$race.area_name, cex.names=0.5, las=3)
# 
# #Scatterplot of the relationship between population size and race
# scatterplot(CAAsiansSubset$Asian, CAAsiansSubset$race.Population, main="California Asian Vote Versus Population", xlim = c(0, 30000), ylim=c(0, 400000))
```


```{r}
# #Helps visualizing missing data
# marginplot(race[c(3, 7)])
# 
# barplot(race$Native.American)
# qqPlot(race$Native.American)
# 
# #Native.American votes versus all populations  
# scatterplot(race$Native.American, race$race.Population, xlim = c(0, 4000000), ylim = c(0,5000000),  xlab="Number of Native.American Votes", ylab="Total Population per County")
# 
# #Wisconsin Native.American Voting whole number values 
# WINativesSubset = subset(race, race.sa=="WI", select = c(race.area_name, race.Population, Native.American, race.sa))
# 
# barplot(WINativesSubset$Native.American, col = rainbow(20), main = "Wisconsin Total Votes by County ", ylab = "Number of Votes",  names.arg =WINativesSubset$race.area_name, cex.names=0.5, las=3)
# 
# #California Native.American Voting whole number values 
# CANativesSubset = subset(race, race.sa=="CA", select = c(race.area_name, race.Population, Native.American, race.sa))
# 
# barplot(CANativesSubset$Native.American, col = rainbow(20), main = "California Total Votes by County ", ylab = "Number of Votes",  names.arg =CANativesSubset$race.area_name, cex.names=0.5, las=3)
# 
# #Scatterplot of the relationship between population size and race
# scatterplot(CANativesSubset$Native.American, CANativesSubset$race.Population, main="California Native.American Vote Versus Population", xlim = c(0, 10000), ylim=c(0, 400000))
```


```{r}
# #Helps visualizing missing data
# marginplot( race[c(3, 9)])
# 
# barplot(race$Pacific.Islander)
# qqPlot(race$Pacific.Islander)
# 
# #Pacific.Islander votes versus all populations  
# scatterplot(race$Pacific.Islander, race$race.Population, xlim = c(0, 4000000), ylim = c(0,5000000),  xlab="Number of Pacific.Islander Votes", ylab="Total Population per County")
# 
# #Wisconsin Pacific.Islander Voting whole number values 
# WIPacIslSubset = subset(race, race.sa=="WI", select = c(race.area_name, race.Population, Pacific.Islander, race.sa))
# 
# barplot(WIPacIslSubset$Pacific.Islander, col = rainbow(20), main = "Wisconsin Total Votes by County ", ylab = "Number of Votes",  names.arg =WIPacIslSubset$race.area_name, cex.names=0.5, las=3)
# 
# #California Pacific.Islander Voting whole number values 
# CAPacIslSubset = subset(race, race.sa=="CA", select = c(race.area_name, race.Population, Pacific.Islander, race.sa))
# 
# barplot(CAPacIslSubset$Pacific.Islander, col = rainbow(20), main = "California Total Votes by County ", ylab = "Number of Votes",  names.arg =CAPacIslSubset$race.area_name, cex.names=0.5, las=3)
# 
# #Scatterplot of the relationship between population size and race
# scatterplot(CAPacIslSubset$Pacific.Islander, CAPacIslSubset$race.Population, main="California Pacific.Islander Vote Versus Population", xlim = c(0, 1500), ylim=c(0, 400000))
```


```{r}
# #Helps visualizing missing data
# marginplot(race[c(3, 10)])
# 
# barplot(race$X2..Races)
# qqPlot(race$X2..Races)
# 
# #X2..Races votes versus all populations  
# scatterplot(race$X2..Races, race$race.Population, xlim = c(0, 4000000), ylim = c(0,5000000),  xlab="Number of X2..Races Votes", ylab="Total Population per County")
# 
# #Wisconsin X2..Races Voting whole number values 
# WIMultiSubset = subset(race, race.sa=="WI", select = c(race.area_name, race.Population, X2..Races, race.sa))
# 
# barplot(WIMultiSubset$X2..Races, col = rainbow(20), main = "Wisconsin Total Votes by County ", ylab = "Number of Votes",  names.arg =WIMultiSubset$race.area_name, cex.names=0.5, las=3)
# 
# #California X2..Races Voting whole number values 
# CAMultiSubset = subset(race, race.sa=="CA", select = c(race.area_name, race.Population, X2..Races, race.sa))
# 
# barplot(CAMultiSubset$X2..Races, col = rainbow(20), main = "California Total Votes by County ", ylab = "Number of Votes",  names.arg =CAMultiSubset$race.area_name, cex.names=0.5, las=3)
# 
# #Scatterplot of the relationship between population size and race
# scatterplot(CAMultiSubset$X2..Races, CAMultiSubset$race.Population, main="California X2..Races Vote Versus Population", xlim = c(0, 20000), ylim=c(0, 400000))

```

```{r}
# #Helps visualizing missing data
# marginplot(race[c(3, 11)])
# 
# barplot(race$Latino)
# qqPlot(race$Latino)
# 
# #Latino votes versus all populations  
# scatterplot(race$Latino, race$race.Population, xlim = c(0, 4000000), ylim = c(0,5000000),  xlab="Number of Latino Votes", ylab="Total Population per County")
# 
# #Wisconsin Latino Voting whole number values 
# WILatinSubset = subset(race, race.sa=="WI", select = c(race.area_name, race.Population, Latino, race.sa))
# 
# barplot(WILatinSubset$Latino, col = rainbow(20), main = "Wisconsin Total Votes by County ", ylab = "Number of Votes",  names.arg =WILatinSubset$race.area_name, cex.names=0.5, las=3)
# 
# #California Latino Voting whole number values 
# CALatinSubset = subset(race, race.sa=="CA", select = c(race.area_name, race.Population, Latino, race.sa))
# 
# barplot(CALatinSubset$Latino, col = rainbow(20), main = "California Total Votes by County ", ylab = "Number of Votes",  names.arg =CALatinSubset$race.area_name, cex.names=0.5, las=3)
# 
# #Scatterplot of the relationship between population size and race
# scatterplot(CALatinSubset$Latino, CALatinSubset$race.Population, main="California Latino Vote Versus Population", xlim = c(0, 300000), ylim=c(0, 400000))

```

```{r}
# #Helps visualizing missing data
# marginplot(race[c(3, 12)])
# 
# barplot(race$White.Not.Latino)
# qqPlot(race$White.Not.Latino)
# 
# #White/Not Latino votes versus all populations  
# scatterplot(race$White.Not.Latino, race$race.Population, xlim = c(0, 4000000), ylim = c(0,5000000),  xlab="Number of White.Not.Latino Votes", ylab="Total Population per County")
# 
# #Wisconsin White/Not Latino Voting whole number values 
# WIEuroSubset = subset(race, race.sa=="WI", select = c(race.area_name, race.Population, White.Not.Latino, race.sa))
# 
# barplot(WIEuroSubset$White.Not.Latino, col = rainbow(20), main = "Wisconsin Total Votes by County ", ylab = "Number of Votes",  names.arg =WIEuroSubset$race.area_name, cex.names=0.5, las=3)
# 
# #California White/Not Latino Voting whole number values 
# CAEuroSubset = subset(race, race.sa=="CA", select = c(race.area_name, race.Population, White.Not.Latino, race.sa))
# 
# barplot(CAEuroSubset$White.Not.Latino, col = rainbow(20), main = "California Total Votes by County ", ylab = "Number of Votes",  names.arg =CAEuroSubset$race.area_name, cex.names=0.5, las=3)
# 
# #Scatterplot of the relationship between population size and race
# scatterplot(CAEuroSubset$White.Not.Latino, CAEuroSubset$race.Population, main="California White.Not.Latino Vote Versus Population", xlim = c(0, 300000), ylim=c(0, 400000))

```




```{r}
set.seed(1)    # for reproducible example
map.county <- map_data('county')
counties   <- unique(map.county[,5:6])
uscounties <- counties
uscounties

wvp= county_facts$RHI125214

white_mapus <- data.frame(state_names=uscounties$region, county_names=uscounties$subregion, wvp75=wvp[1:3076])


map.county <- data.table(map.county)
setkey(map.county,region,subregion)
white_mapus <- data.table(white_mapus)
setkey(white_mapus,state_names,county_names)
map.dfus      <- map.county[white_mapus]

ggplot(map.dfus, aes(x=long, y=lat, group=group, fill=wvp75), color = "black") + geom_polygon()+coord_map() + 
  borders(database = "county")

akmap.county <- map_data('county')
counties   <- unique(map.county[,5:6])
akcounties <- counties[counties$region=="arkansas",]
akcounties

white_map <- data.frame(state_names=akcounties$region,                  county_names=akcounties$subregion,wvp75=wvp[c(1:74, 1)])


akmap.county <- data.table(akmap.county[akmap.county$region=="arkansas",])
setkey(akmap.county,region,subregion)
white_mapak <- data.table(white_map)
setkey(white_mapak,state_names,county_names)
map.dfak      <- akmap.county[white_mapak]

ggplot(map.dfak, aes(x=long, y=lat, group=group, fill=wvp75)) + geom_polygon()+coord_map()

set.seed(1)    # for reproducible example
wimap.county <- map_data('county')
counties   <- unique(wimap.county[,5:6])
wicounties <- counties[counties$region=="wisconsin",]
wicounties

wiwhite_map <- data.frame(state_names=wicounties$region,                  county_names=wicounties$subregion,WIWhiteVotePercent=wvp[c(1:71, 1)])

wimap.county <- data.table(map.county[map.county$region=="wisconsin",])
setkey(wimap.county,region,subregion)
wiwhite_map <- data.table(wiwhite_map)
setkey(wiwhite_map,state_names,county_names)
map.dfwi      <- wimap.county[wiwhite_map]

ggplot(map.dfwi, aes(x=long, y=lat, group=group, fill=WIWhiteVotePercent)) + geom_polygon()+coord_map()

```


```{r}
#Graphs of the democrats vs republic coutnies won
classcolors <- c('red', 'cyan' )

usmapDvR=map('county', fill= TRUE, col = classcolors[pe16rwvd9$lead]) 

map('county', "wisconsin", fill= TRUE, col = classcolors[pe16rwvd9$lead]) 

map('county', "California", fill= TRUE, col = classcolors[pe16rwvd9$lead])

map('county', "New York", fill= TRUE, col = classcolors[pe16rwvd9$lead])
```



```{r}
#Subsetting Trumps, Hillary and others votes

hcperc = pe16rwvd9$Hillary.Clinton/pe16rwvd9$total_votes
dtperc = pe16rwvd9$Donald.Trump/pe16rwvd9$total_votes

maincands=subset(pe16rwvd9[-1,], select = c(county, total_votes, lead, Hillary.Clinton, Donald.Trump))

maincands=cbind(maincands, hcperc[-1], dtperc[-1])

maincands= maincands[c(1, 2,3, 4, 6, 5, 7)]


```

```{r}
#Showing the level of support of Donald Trump in each county.
#Wyoming shows the lightest shade of Blue, representing the higher support for Trump
#Arkansas shows the lowest 

set.seed(1)
map.county <- map_data('county')
counties   <- unique(map.county[,5:6])
```


```{r}
dont = maincands$`dtperc[-1]`

trumpsupport <- data.frame(state_names=counties$region, county_names=counties$subregion, dontrus=dont[1:3076])

map.county <- data.table(map.county)
setkey(map.county,region,subregion)
trumpsupport <- data.table(trumpsupport)
setkey(trumpsupport,state_names,county_names)
map.dftrump      <- map.county[trumpsupport]

ggplot(map.dftrump,  aes(x=long, y=lat, group=group, fill=dontrus), color = "black") + geom_polygon()+coord_map() + 
  borders(database = "county") + ggtitle("Donald Trump County Support in Percentages") + scale_color_gradient(low="blue", high="red", na.value = "grey50")


```

```{r}
#Showing the level of support of Donald hillary in each county.
#Wyoming shows the lightest shade of Blue, representing the higher support for hillary
#Arkansas shows the lowest 


hicl = maincands$`hcperc[-1]`

clintonsupport <- data.frame(state_names=counties$region, county_names=counties$subregion, hilclin=hicl[1:3076])

map.county <- data.table(map.county)
setkey(map.county,region,subregion)
clintonsupport <- data.table(clintonsupport)
setkey(clintonsupport,state_names,county_names)
map.dfclinton      <- map.county[clintonsupport]

ggplot(map.dfclinton,  aes(x=long, y=lat, group=group, fill=hilclin), color = "white") + geom_polygon()+coord_map() + 
  borders(database = "county") + ggtitle("Hillary Clinton County Support in Percentages") + scale_color_gradient(low="blue", high="red", na.value = "grey50")


```

